extends:
  - '@gitlab'
globals:
  __webpack_public_path__: true
  gl: false
  gon: false
  localStorage: false
plugins:
  - import
  - html
  - vanilla-i18n
settings:
  import/resolver:
    webpack:
      config: './config/webpack.config.js'
rules:
  vanilla-i18n/detect-non-i18n-string: error
  import/no-commonjs: error
  no-underscore-dangle:
    - error
    - allow:
        - __
        - _links
  # Disabled for now, to make the airbnb-base 12.1.0 -> 13.1.0 update smoother
  no-else-return:
    - error
    - allowElseIf: true
  import/no-useless-path-segments: off
  lines-between-class-members: off
  # Disabled for now, to make the plugin-vue 4.5 -> 5.0 update smoother
  vue/no-confusing-v-for-v-if: error
  vue/no-unused-components: off
  vue/no-use-v-if-with-v-for: off
  vue/no-v-html: off
  vue/use-v-on-exact: off
overrides:
  files: 
    - '*.vue'
    - 'spec/**'
  rules: 
    vanilla-i18n/detect-non-i18n-string: off
